<?php

namespace Database\Seeders\Admin;

use App\Models\Admin\SetupPage;
use Illuminate\Database\Seeder;

class SetupPageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $setup_pages = array(
            array('id' => '1','type' => 'setup-page','slug' => 'home','title' => 'Home','url' => '/','details' => NULL,'last_edit_by' => '1','status' => '1','created_at' => '2023-09-23 08:47:27','updated_at' => NULL),
            array('id' => '2','type' => 'setup-page','slug' => 'about-us','title' => 'About','url' => '/about-us','details' => NULL,'last_edit_by' => '1','status' => '1','created_at' => '2023-09-23 08:47:27','updated_at' => NULL),
            array('id' => '3','type' => 'setup-page','slug' => 'our-services','title' => 'Services','url' => '/services','details' => NULL,'last_edit_by' => '1','status' => '1','created_at' => '2023-09-23 08:47:27','updated_at' => NULL),
            array('id' => '4','type' => 'setup-page','slug' => 'features','title' => 'Features','url' => '/features','details' => NULL,'last_edit_by' => '1','status' => '1','created_at' => '2023-09-23 08:47:27','updated_at' => NULL),
            array('id' => '5','type' => 'setup-page','slug' => 'blogs','title' => 'Blog','url' => '/blogs','details' => NULL,'last_edit_by' => '1','status' => '1','created_at' => '2023-09-23 08:47:27','updated_at' => NULL),
            array('id' => '6','type' => 'setup-page','slug' => 'contact-us','title' => 'Contact','url' => '/contact-us','details' => NULL,'last_edit_by' => '1','status' => '1','created_at' => '2023-09-23 08:47:27','updated_at' => NULL),
            array('id' => '7','type' => 'useful-links','slug' => 'privacy-policy','title' => 'Privacy Policy','url' => NULL,'details' => '<h3 style="margin-left:0px;"><strong>What information do we collect?</strong></h3><p style="margin-left:0px;">We gather data from you when you register on our site, submit a request, buy any services, react to an overview, or round out a structure. At the point when requesting any assistance or enrolling on our site, as suitable, you might be approached to enter your: name, email address, or telephone number. You may, nonetheless, visit our site anonymously.</p><h3 style="margin-left:0px;"><strong>How do we protect your information?</strong></h3><p style="margin-left:0px;">All provided delicate/credit data is sent through Stripe.<br>After an exchange, your private data (credit cards, social security numbers, financials, and so on) won be put away on our workers.</p><h3 style="margin-left:0px;"><strong>Do we disclose any information to outside parties?</strong></h3><p style="margin-left:0px;">We don sell, exchange, or in any case move to outside gatherings by and by recognizable data. This does exclude confided in outsiders who help us in working our site, leading our business, or adjusting you, since those gatherings consent to keep this data private. We may likewise deliver your data when we accept discharge is suitable to follow the law, implement our site strategies, or ensure our own or others rights, property, or wellbeing.</p><h3 style="margin-left:0px;"><strong>Childrens Online Privacy Protection Act Compliance</strong></h3><p style="margin-left:0px;">We are consistent with the prerequisites of COPPA (Childrens Online Privacy Protection Act), we don gather any data from anybody under 13 years old. Our site, items, and administrations are completely coordinated to individuals who are in any event 13 years of age or more established.</p><h3 style="margin-left:0px;"><strong>Changes to our Privacy Policy</strong></h3><p style="margin-left:0px;">If we decide to change our privacy policy, we will post those changes on this page.</p><h3 style="margin-left:0px;"><strong>How long we retain your information?</strong></h3><p style="margin-left:0px;">At the point when you register for our site, we cycle and keep your information we have about you however long you don not erase the record or withdraw yourself (subject to laws and guidelines).</p>','last_edit_by' => NULL,'status' => '1','created_at' => NULL,'updated_at' => '2023-12-10 12:04:05'),
            array('id' => '8','type' => 'useful-links','slug' => 'refund-policy','title' => 'Refund Policy','url' => NULL,'details' => '<h3 style="margin-left:0px;"><strong>What information do we collect?</strong></h3><p style="margin-left:0px;">We gather data from you when you register on our site, submit a request, buy any services, react to an overview, or round out a structure. At the point when requesting any assistance or enrolling on our site, as suitable, you might be approached to enter your: name, email address, or telephone number. You may, nonetheless, visit our site anonymously.</p><h3 style="margin-left:0px;"><strong>How do we protect your information?</strong></h3><p style="margin-left:0px;">All provided delicate/credit data is sent through Stripe.<br>After an exchange, your private data (credit cards, social security numbers, financials, and so on) won be put away on our workers.</p><h3 style="margin-left:0px;"><strong>Do we disclose any information to outside parties?</strong></h3><p style="margin-left:0px;">We don sell, exchange, or in any case move to outside gatherings by and by recognizable data. This does exclude confided in outsiders who help us in working our site, leading our business, or adjusting you, since those gatherings consent to keep this data private. We may likewise deliver your data when we accept discharge is suitable to follow the law, implement our site strategies, or ensure our own or others rights, property, or wellbeing.</p><h3 style="margin-left:0px;"><strong>Childrens Online Privacy Protection Act Compliance</strong></h3><p style="margin-left:0px;">We are consistent with the prerequisites of COPPA (Childrens Online Privacy Protection Act), we don gather any data from anybody under 13 years old. Our site, items, and administrations are completely coordinated to individuals who are in any event 13 years of age or more established.</p><h3 style="margin-left:0px;"><strong>Changes to our Privacy Policy</strong></h3><p style="margin-left:0px;">If we decide to change our privacy policy, we will post those changes on this page.</p><h3 style="margin-left:0px;"><strong>How long we retain your information?</strong></h3><p style="margin-left:0px;">At the point when you register for our site, we cycle and keep your information we have about you however long you don not erase the record or withdraw yourself (subject to laws and guidelines).</p>','last_edit_by' => NULL,'status' => '1','created_at' => NULL,'updated_at' => '2023-12-10 12:08:54'),
            array('id' => '9','type' => 'useful-links','slug' => 'terms-and-conditions','title' => 'Terms & Conditions','url' => NULL,'details' => '<h3 style="margin-left:0px;"><strong>What information do we collect?</strong></h3><p style="margin-left:0px;">We gather data from you when you register on our site, submit a request, buy any services, react to an overview, or round out a structure. At the point when requesting any assistance or enrolling on our site, as suitable, you might be approached to enter your: name, email address, or telephone number. You may, nonetheless, visit our site anonymously.</p><h3 style="margin-left:0px;"><strong>How do we protect your information?</strong></h3><p style="margin-left:0px;">All provided delicate/credit data is sent through Stripe.<br>After an exchange, your private data (credit cards, social security numbers, financials, and so on) won be put away on our workers.</p><h3 style="margin-left:0px;"><strong>Do we disclose any information to outside parties?</strong></h3><p style="margin-left:0px;">We don sell, exchange, or in any case move to outside gatherings by and by recognizable data. This does exclude confided in outsiders who help us in working our site, leading our business, or adjusting you, since those gatherings consent to keep this data private. We may likewise deliver your data when we accept discharge is suitable to follow the law, implement our site strategies, or ensure our own or others rights, property, or wellbeing.</p><h3 style="margin-left:0px;"><strong>Childrens Online Privacy Protection Act Compliance</strong></h3><p style="margin-left:0px;">We are consistent with the prerequisites of COPPA (Childrens Online Privacy Protection Act), we don gather any data from anybody under 13 years old. Our site, items, and administrations are completely coordinated to individuals who are in any event 13 years of age or more established.</p><h3 style="margin-left:0px;"><strong>Changes to our Privacy Policy</strong></h3><p style="margin-left:0px;">If we decide to change our privacy policy, we will post those changes on this page.</p><h3 style="margin-left:0px;"><strong>How long we retain your information?</strong></h3><p style="margin-left:0px;">At the point when you register for our site, we cycle and keep your information we have about you however long you don not erase the record or withdraw yourself (subject to laws and guidelines).</p>','last_edit_by' => NULL,'status' => '1','created_at' => NULL,'updated_at' => '2023-12-10 12:08:18')
          );
        SetupPage::insert($setup_pages);
    }
}
